# Generated by Django 4.0.6 on 2022-07-18 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_delete_address'),
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='access',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='authenticate.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_HOD',
            field=models.BooleanField(default=False),
        ),
    ]
