# Generated by Django 4.0.4 on 2022-07-06 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authenticate', '0003_delete_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(choices=[('M.Tech', 'M.Tech'), ('B.Tech', 'B.Tech'), ('Diploma', 'Diploma')], default='B.Tech', max_length=8)),
                ('course_duration', models.CharField(choices=[('4 years', '4 years'), ('3 years', '3 years'), ('2 years', '2 years')], default='4 years', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.CharField(max_length=6)),
                ('end_year', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6)),
                ('role_number', models.IntegerField()),
                ('phone', models.IntegerField(max_length=10)),
                ('blood_group', models.CharField(max_length=20)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='authenticate.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('CSE', 'Computer Science & Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('EE', 'Electrical Engineering')], default='ME', max_length=5)),
                ('year_id', models.CharField(default='1st year', max_length=6)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='Student.course')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='Student.session')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_1', models.CharField(max_length=200)),
                ('line_2', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.IntegerField(max_length=10)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='authenticate.customuser')),
            ],
        ),
    ]
