# Generated by Django 4.0.4 on 2022-07-07 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_rename_user_id_student_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='student_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='Student.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='year_id',
            field=models.CharField(default='1st year', max_length=10),
        ),
    ]
