# Generated by Django 4.0.6 on 2022-07-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_class_student_id_alter_class_year_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='session_id',
            new_name='session',
        ),
        migrations.RemoveField(
            model_name='class',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='class',
            name='year_id',
        ),
        migrations.AddField(
            model_name='class',
            name='year',
            field=models.CharField(choices=[('1st year', '1st year'), ('2nd year', '2nd year'), ('3rd year', '3rd year'), ('4th year', '4th year')], default='1st year', max_length=9),
        ),
    ]
