# Generated by Django 4.0.6 on 2022-07-12 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0001_initial'),
        ('Student', '0005_student_class_mapper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('subject_code', models.IntegerField()),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='Student.class')),
                ('subject_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='Teacher.teacher')),
            ],
        ),
    ]
