# Generated by Django 4.0.6 on 2022-07-19 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0007_alter_class_course_alter_class_session_and_more'),
        ('Attendance', '0002_alter_attendance_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_attendance',
            name='attendance',
        ),
        migrations.AddField(
            model_name='student_attendance',
            name='attend',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='present', to='Attendance.attendance'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student_attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner', to='Student.student'),
        ),
    ]
