# Generated by Django 4.0.6 on 2022-07-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0003_remove_student_attendance_attendance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_attendance',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
    ]
