# Generated by Django 4.0.6 on 2022-07-19 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0007_alter_class_course_alter_class_session_and_more'),
        ('Attendance', '0004_alter_student_attendance_is_present'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_attendance',
            name='attend',
        ),
        migrations.AddField(
            model_name='student_attendance',
            name='attendance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='studentattendance', to='Attendance.attendance'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='Student.subject'),
        ),
    ]
